import './globals.scss'
import Link from 'next/link'
import LoginBtn from './LoginBtn'
import LogoutBtn from './LogoutBtn'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import Register from './register/page'
import Head from 'next/head'



export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

    let session= await getServerSession(authOptions)
    if(session){
        console.log(session)
    }

    return (
        <html lang="en">
            <Head>
                <title>next shopping</title>
                <meta charset='utf-8' />
                <meta name='viewport' content='width=device-width, initial-scale=1.0' /> 
                <meta name='Title' content='' />
                <meta name='Subject' content='' />
                <meta name='Keywords' content='로그인 만들기, db생성,회원가입 만들기' />
                <meta name='Author' content='' />
                <meta name='Publisher' content='수민' />
                <meta name='Description' content='next.js를 사용하여 쇼핑몰 만들기' />
                <meta name='Author-Date' content='23.09.14' />
                <meta name='Copyright' content='COPYRIGHT &copy; SOOMIN ALL RIGHT RESERVED.' />
            </Head>
            <body>
                <div className='top-nav'>
                    <div className="logo">
                        <Link href="/"><img src="/img/logo.png" alt="logo" /></Link>
                    </div>
                    <div className="g-menu">
                        <ul>
                            <li>{session ? <LogoutBtn />: <LoginBtn />}</li>
                            <li><Link href="/register">JOIN</Link></li>
                            <li><Link href="/cart">CART</Link></li>
                            <li><Link href="/notice">NOTICE</Link></li>
                        </ul>
                    </div>
                </div>
                {/* .side-nav component로 수정하기 */}
                <nav className='side-nav'>
                    <ul>
                        <li><Link href='/new'>NEW</Link></li>
                        <li><Link href='/all'>ALL</Link></li>
                        <li><Link href='/outweat'>OUTWEAR</Link></li>
                        <li><Link href='/tops'>TOP</Link></li>
                        <li><Link href='/kint'>KNIT</Link></li>
                        <li><Link href='/bottoms'>BOTTOM</Link></li>
                        <li><Link href='/acc'>ACC</Link></li>
                    </ul>
                </nav>
                {children}
                <div className="footer">
                    <div className="footer-inner">
                        <ul className='footer-left'>
                            <li>
                                <h4>COMPANY INFOMATION</h4>
                                <ul>
                                    <li><Link href="/">Company. soom</Link></li>
                                    <li><Link href="/">Address. 서울 용산구</Link></li>
                                    <li><Link href="/">Business Number. 204-12-</Link></li>
                                    <li><Link href="/">CopyRight &copy; soom All Rights Reserved.</Link></li>
                                </ul>
                            </li>
                            <li>
                                <h4>About Us</h4>
                                <ul>
                                    <li><Link href="/">회사소개</Link></li>
                                    <li><Link href="/">이용약관</Link></li>
                                    <li><Link href="/">개인정보 취급 방침</Link></li>
                                    <li><Link href="/">협찬/제휴문의</Link></li>
                                </ul>
                            </li>
                        </ul>
                        <ul className='footer-right'>
                            <li>
                                <h4>Customer Services</h4>
                                <ul>
                                    <li>Monday-Friday 10:00-17:00 (break 12:00-13:00)</li>
                                    <li>Tel. 070-4774-3574</li>
                                    <li><span>게시판을 이용해주시면 빠르게 답변 가능합니다.</span></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </body>
        </html>
    )
}
